### ISSUE TITLE
How to execute?

### ISSUE THREAD

**Issue by JonnyTech** [horar/homebrew-openconnect-gui#1]
How do I run `openconnect-gui` after installing it? I have tried `openconnect-gui` from the terminal command-line and searched for it with spotlight but cannot find a way to execute the program.

**Comment by michaelblyons** [comment]
The formula builds a `.app` that you want to copy to your Applications folder. Something like

```sh
cp "$(brew --prefix)/Cellar/openconnect-gui/build-release/bin/OpenConnect-GUI.app" /Applications
```
although I probably have the paths slightly wrong.

**Comment by schniggie** [comment]
`open /usr/local/Cellar/openconnect-gui/1.5.3/OpenConnect-GUI.app` will do the trick :)

**Comment by JonnyTech** [comment]
Thanks, I had forgotten about this old issue. IIRC it was a path and dependancy issue. Differences on Linux and Mac. Closing.
