### ISSUE TITLE
Openconnect GUI 1.5.4 support?

### ISSUE THREAD

**Issue by yermulnik** [horar/homebrew-openconnect-gui#3]
Is there any chance to get formulae bumped to latest openconnect gui version which is 1.5.4 and is available from [GitLab](https://gitlab.com/openconnect/openconnect-gui/-/releases/v1.5.4) rather than from GitHub (seems like GH mirror has stepped down 😢 )?

Please let me know how can I help/assist (I'm very new to MacOS and Brew though 🤷 )

Thanks in advance.

**Comment by michaelblyons** [comment]
The 1.5.4 tag doesn't exist in GitLab either (Click on any 1.5.4 release link to see). And GitLab doesn't have builds anyway, only source code. If you want a newer version, you'll have to build it yourself.

It _might_ work to `brew install --head openconnect-gui` if you have this repo tapped. But I can't guarantee it. CMake or Qt may have upgraded to an incompatible version.

**Comment by yermulnik** [comment]
Oh, didn't try to follow 1.5.4 release links in GitLab. Odd.
Anyways thanks for the formulae and for the pointers. And yep, I already managed to `brew install --HEAD --with-ini-settings openconnect-gui` it with this repo being tapped – worked with more or less friction (had to install Xcode, had to convince MacOS I've got `git-lfs` installed, had to manually locate app binary from installation dir, etc). And it works.

For those who will come across this "issue": 1) unfortunately Openconnect-GUI code from HEAD branch has a glitch where `Minimize / Restore` isn't working and always "thinks" app is minimised despite of app state (can open app window via dock icon only) and 2) it also is missing an option to pass additional cmdline params to underlying `openconnect` binary which I do need to trick Global Protect and pretend I'm on Linux to force it to switch to interactive mode (maybe my company's specific setting or something Global Protect related – 🤷 ).

**Comment by horar** [comment]
Hi, thanks for pointing this, I will all handle it after Holidays (I guess 1.5.4/1.6.0 tags was created on migration to GitLab)

**Comment by yermulnik** [comment]
@horar Thanks a lot, much appreciated! Have a nice Holidays :partying_face:

**Comment by horar** [comment]
hey, just take a quick look; v1.5.4/1.6.0 was internal preview tags; after migration to GitLab the script create a public releases.
Anyway, I believe it's time to generate next official release...
